steps:
  # Build API container for Cloud Run
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'build'
      - '-f'
      - './backend/apps/api/Dockerfile.cloudrun'
      - '-t'
      - 'gcr.io/$PROJECT_ID/video-enhancer-api:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/video-enhancer-api:latest'
      - './backend/apps/api'
  
  # Push to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/video-enhancer-api:$COMMIT_SHA']
  
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/video-enhancer-api:latest']
  
  # Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
    - 'run'
    - 'deploy'
    - 'video-enhancer-api'
    - '--image'
    - 'gcr.io/$PROJECT_ID/video-enhancer-api:$COMMIT_SHA'
    - '--region'
    - 'us-central1'
    - '--platform'
    - 'managed'
    - '--allow-unauthenticated'
    - '--port'
    - '3000'
    - '--memory'
    - '1Gi'
    - '--cpu'
    - '1'
    - '--min-instances'
    - '0'
    - '--max-instances'
    - '10'
    - '--timeout'
    - '300'
    - '--concurrency'
    - '80'

# Store images in Container Registry
images:
  - 'gcr.io/$PROJECT_ID/video-enhancer-api:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/video-enhancer-api:latest'

# Build configuration
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'